### PR TITLE
fix: Do not panic when /proc/modules does not exist

### LINKED ISSUE #138: aborts when no modules present
in this case under lxc on a chromebook (and probably on generic linux in a few other cases eg with no runtime modules) there is no `/proc/modules`, so this panic's. In this case could it just return and empty string so it would not panic, and then show an empty set of modules? 

https://github.com/orhun/kmon/blob/3ed516fcbfe6600d27287e49545f023e9736a200/src/kernel/lkm.rs#L117-L118

### PR DESCRIPTION
**Pull request by eld4niz**
## Description
As it mentioned in issue I linked below, chromebooks and few types of generic linux kernels does not include `/proc/modules` so program panics.

## Motivation and Context
fixes #138

I'll also implement parsing to return empty set of modules.

## How Has This Been Tested?
I couldn't test this bug fix, because I don't use chromebook or generic linux kernel, so I hope who created issue can test on his device. If there are any ways to reproduce that kernel types please let me know :)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] [Rustfmt](https://github.com/rust-lang/rustfmt) and [Rust-clippy](https://github.com/rust-lang/rust-clippy) passed.

### CODE REVIEW

**Comment by orhun** [comment]
> I'll also implement parsing to return empty set of modules.

Does that you will follow up with another PR?

File: src/kernel/lkm.rs [hunk 1]
```diff
@@ -115,7 +115,7 @@ impl KernelModules<'_> {
 			_ => {}
 		}
 		let modules_content = util::exec_cmd("sh", &["-c", &module_read_cmd])
-			.expect("failed to read /proc/modules");
+			.unwrap_or_else(|_| String::new());
```
Comment (orhun) [inline src/kernel/lkm.rs:118]: LGTM!

Maybe we can also log the error on the first run. Since pressing `r` would print it again while running the TUI.

Something like this:

```rust
		let modules_content = match util::exec_cmd("sh", &["-c", &module_read_cmd]) {
			Ok(v) => v,
			Err(e) => {
				eprintln!("{e}");
				String::new()
			}
		};
```

What do you think?

Comment (eld4niz) [reply src/kernel/lkm.rs:118]: yes, this is definitely better way to do it. I just tried the first version that comes to my mind :)

**Comment by eld4niz** [comment]
Yes. I'll try to add it with another PR. 
Now I'm trying to find a way to solve termion problem: https://github.com/ratatui-org/ratatui/issues/1005

File: src/kernel/lkm.rs [hunk 2]
```diff
@@ -114,8 +114,13 @@ impl KernelModules<'_> {
 			SortType::Dependent => module_read_cmd += " | sort -n -r -t ' ' -k3",
 			_ => {}
 		}
-		let modules_content = util::exec_cmd("sh", &["-c", &module_read_cmd])
-			.expect("failed to read /proc/modules");
+		let modules_content = match util::exec_cmd("sh", &["-c", &module_read_cmd]) {
+			Ok(v) => v,
+			Err(e) => {
+				eprintln!("{e}");
```
Comment (orhun) [inline src/kernel/lkm.rs:120]: As I mentioned, the only problem with this approach is that you'll see the error message every time you press `r` (thus messes up the TUI) - so I suggest we don't print the error here.

We call this function for first time in `KernelModules::new` - maybe that's a good place to print the error before we even launch the TUI.

What do you think?

Comment (eld4niz) [reply src/kernel/lkm.rs:120]: You mean handling that in the mod.rs file?

Comment (orhun) [reply src/kernel/lkm.rs:120]: No I meant in the same file (`lkm.rs`), a little above. We can handle it in `mod.rs` too I guess. The point is we only print the error once.

Comment (orhun) [reply src/kernel/lkm.rs:120]: btw let me know if you need any guidance doing that - the codebase is kind of old and hard to figure out sometimes (I'm having issues myself lol)

Comment (eld4niz) [reply src/kernel/lkm.rs:120]: I tried to do this within `new()` function in `lmk.rs`, but couldn't figure out how should I do that, because we don't call module_content in there. What kind of ways should I consider?

Comment (orhun) [reply src/kernel/lkm.rs:120]: It turned out to be a bit more complicated than what I initially proposed, but we can simply apply this patch:


```diff
commit 06c0eb9dbd85e827d227964614ad6bdb3a7bab8f
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sun Apr 7 00:01:16 2024 +0300

    refactor: Suppress refresh error

diff --git a/src/kernel/lkm.rs b/src/kernel/lkm.rs
index 3315003..c08bac6 100644
--- a/src/kernel/lkm.rs
+++ b/src/kernel/lkm.rs
@@ -5,6 +5,7 @@ use crate::util;
 use bytesize::ByteSize;
 use clap::ArgMatches;
 use ratatui::text::{Line, Span, Text};
+use std::error::Error;
 use std::slice::Iter;
 
 /* Type of the sorting of module list */
@@ -99,12 +100,14 @@ impl KernelModules<'_> {
 			args,
 			style,
 		};
-		kernel_modules.refresh();
+		if let Err(e) = kernel_modules.refresh() {
+			eprintln!("{e}");
+		}
 		kernel_modules
 	}
 
 	/* Parse kernel modules from '/proc/modules'. */
-	pub fn refresh(&mut self) {
+	pub fn refresh(&mut self) -> Result<(), Box<dyn Error>> {
 		let mut module_list: Vec<Vec<String>> = Vec::new();
 		/* Set the command for reading kernel modules and execute it. */
 		let mut module_read_cmd = String::from("cat /proc/modules");
@@ -114,13 +117,7 @@ impl KernelModules<'_> {
 			SortType::Dependent => module_read_cmd += " | sort -n -r -t ' ' -k3",
 			_ => {}
 		}
-		let modules_content = match util::exec_cmd("sh", &["-c", &module_read_cmd]) {
-			Ok(v) => v,
-			Err(e) => {
-				eprintln!("{e}");
-				String::new()
-			}
-		};
+		let modules_content = util::exec_cmd("sh", &["-c", &module_read_cmd])?;
 		/* Parse content for module name, size and related information. */
 		for line in modules_content.lines() {
 			let columns: Vec<&str> = line.split_whitespace().collect();
@@ -143,6 +140,8 @@ impl KernelModules<'_> {
 		self.default_list = module_list.clone();
 		self.list = module_list;
 		self.scroll_list(ScrollDirection::Top);
+
+		Ok(())
 	}
 
 	/**
diff --git a/src/kernel/mod.rs b/src/kernel/mod.rs
index dd55b33..e7b2446 100644
--- a/src/kernel/mod.rs
+++ b/src/kernel/mod.rs
@@ -34,6 +34,6 @@ impl Kernel {
 	pub fn refresh(&mut self) {
 		self.logs.refresh();
 		self.info.refresh();
-		self.modules.refresh();
+		let _ = self.modules.refresh();
 	}
 }
```

Here we still return the error, but print the error when `KernelModules` is constructed and suppress it for the `refresh` function.

Comment (eld4niz) [reply src/kernel/lkm.rs]: @orhun I applied your changes

Comment (eld4niz) [reply src/kernel/lkm.rs]: but as I said before I couldn't test it because I can't reproduce that kernel type

Comment (orhun) [reply src/kernel/lkm.rs]: that's fine, you can return a dummy error from that function (via `panic!`) just for testing 🙂

**Review by orhun — APPROVED** [review]
Thanks!
